[profile.default]
# Directory containing smart contracts
src = "contracts"

# Out directory for compiled contracts
out = "out"

# Directory for test files
test = "test"

# Directory for libraries
libs = ["lib"]

# Solidity compiler version
solc_version = "0.8.20"
via_ir = true
optimizer = true
optimizer_runs = 200
